/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.example.app

import org.example.utilities.StringUtils

import org.apache.commons.text.WordUtils

fun main() {
    val tokens = StringUtils.split(MessageUtils.getMessage())
    val result = StringUtils.join(tokens)
    println(WordUtils.capitalize(result))

    lateinit var largura: String;
    lateinit var altura : String;
    var area : Double;

    altura = "5.0"
    largura = "6.0"

    area = altura.toDouble() * largura.toDouble()

    println(area)

    var name = "Louise"
    var age = 16

    var example: ExampleInterface = ExampleClass(age, name)

    example.nameExample = "Louise"
    example.variableExample = 16

    println(example.init())
    println(example.final())

    val isEven = object : FunIntExample {
        override fun convert(i: Int): Boolean {
            return i % 2 == 0
        }
    }






}
